### ISSUE TITLE
Failure on block change

### ISSUE THREAD

**Issue by EnderEth** [tiagoshibata/methminer#3]
Hi,
I’m testing your program on several mining pc , since 1 day, it occurs a problem on block change 14399999 to 14400000 the program hangs on all pc’s.
Best regards,

**Comment by tiagoshibata** [comment]
Can you give me a full command line that reproduces the hang? Thanks!

**Comment by EnderEth** [comment]
Hi Tiago, thanks for your rapid answer, it was at midnight so I couldn’t take screenshots
I have let run also one ethminer (2 months ago by Arda Coskunses [master](https://github.com/ethereum-mining/ethminer/tree/master) [63cf9afd](https://github.com/ethereum-mining/ethminer/commit/63cf9afd368c2227d6c169252a0978c1c2abadd2) ← [cmdLine](https://github.com/ardacoskunses/ethminer/tree/cmdLine) [726eb1ac](https://github.com/ardacoskunses/ethminer/commit/726eb1aca578f6929cf01b179a9ae1cba365bc8f))  this has no problems.
So I will run one of the machines with your program again, should the problem occurs again I will take a screenshot.
Best regards,
this is the command line:

methminer.exe --HWMON 0 -P stratum2+ssl://wallet.workername:x@eu1.ethermine.org:5555 stratum2+ssl://wallet.workername:x@eu1.ethermine.org:5555 -R -G --exit --devices 0 1 2 3 4 5 6 7 --seq -v 1 --
retry-delay 10 --work-timeout 500 --response-timeout 60 
pause

**Comment by Boz4001** [comment]
![screenshot-1](https://user-images.githubusercontent.com/92085031/159221615-98c60311-a3fb-4217-9a1c-134ac116a637.png)

**Comment by Boz4001** [comment]
On event viewer following errors:
faulty module path: C:\Windows\System32\ucrtbase.dll
Windows error: insufficient virtual memory caused by methminer.exe

**Comment by tiagoshibata** [comment]
I only use the Linux builds myself. If you're willing to root-cause the issue and propose a fix I'm open to reviewing and merging the PR.

**Comment by EnderEth** [comment]
Hi Tiago, thanks for your response, I am testing many miner programs, I think that this with no fee’s are the fastest, yours also.
I will use your program, so I will give you the decision to check what happens or not.
Maybe you can serve us with a Microsoft compiled version, so I can test it first; maybe it is a compile issue.
PS: All based NSF-miners have higher stale rate, but it’s not a big problem for me.
Best regards,
